### PR TITLE
Rename js files to jsx

### PR DESCRIPTION
**Pull request by ArturSharapov**
It's better to not force every project that uses this package to configure their build tools to treat `js` files as `jsx`, which is the only way to get this package working! Some projects or frameworks do not have support for [optimizeDeps](https://github.com/vitejs/vite/issues/4427) (which is a case in Astro, for example) and so defining a custom loader might be a little [painful](https://github.com/vitejs/vite/discussions/3448#discussioncomment-749919). 

This PR only renames `js` source files to `jsx` and gets rid of the loader option in the esbuild build configuration.

---

Verified it's still working locally with the `example:dev`.
Tested in an Astro project with the following required configuration:
```
vite: {
  esbuild: {
    jsx: 'automatic',
    jsxImportSource: 'preact',
  },
}
```

### CODE REVIEW

**Comment by barelyhuman** [comment]
Fair ask but I was thinking of giving the transpiled files instead of the JSX files. i have projects that can't transpile at all and I have been lazing on that for a while now. 

i'll be picking up this project again from Thursday so should be able to simplify a lot of things for actual production usage.

**Comment by ArturSharapov** [comment]
> giving the transpiled files instead of the JSX files

Of course. This was just a quick fix to have it working for an astro project. Will be using github direct import for now then.

**Comment by barelyhuman** [comment]
Well, you can install `0.0.3-beta.1` instead

**Comment by ArturSharapov** [comment]
Thank you! Made a quick migration to vite and pnpm [here](https://github.com/ArturSharapov/datepicker/tree/vite). If you're okay with using vite instead of custom esbuild script file directly, please let me know and I'll submit another PR. Feel free to make edits or just tell me what things you'd like to have different..

**Comment by ArturSharapov** [comment]
Oh, I've just seen you made your own edits already in #3. That was earlier than Thursday 😄
You can ignore my comment above then.

**Comment by barelyhuman** [comment]
Well I am at the airport with a decent wifi so though I'd at least avoid you the headache of using repository package resolution

**Comment by ArturSharapov** [comment]
> the headache of using GitHub package resolution

It was actually as simple as setting
```json
"@preachjs/datepicker": "github:ArturSharapov/datepicker"
```
in package.json, but thank you, very appreciate it!

The vite & pnpm might offer a better DX however, so please have a look if you get a chance (def not urgent at all). Maybe just copy prettier and husky, update contribution.md, and it should be good.

**Comment by barelyhuman** [comment]
Make sure you add the build part in your ‘prepare’ script to avoid an asset missing issue. 


I like to keep tooling simple and add configs as needed, might add esbuild-multicontext if we get to a stage where tsc starts becoming too slow

**Comment by barelyhuman** [comment]
Closing this,`v0.0.3` has a proper publish step

**Pull request closed without merging**
